### ISSUE TITLE
If user_id is in recipients, do not record a commission

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#101]
See https://github.com/chriscct7/edd-fes/issues/928

**Comment by pippinsplugins** [comment]
Hmm, not sure on this. Could go both ways.

I test commission creation with my own user all the time.

**Comment by SDavisMedia** [comment]
Yea I do too.

**Comment by pippinsplugins** [comment]
Personally, I'd vote that we not do this.

**Comment by SDavisMedia** [comment]
The problem presented by a user is that commissions can be recorded for a vendor after purchasing his or her own product. They could then get money back. But at the same time, earn points through Points & Rewards for their purchase. Then use the points for discounts on products that do not belong to them.

Crazy? Sure. Possible? Absolutely. And because FES, Commissions, and Points & Rewards are all part of the same bundle, I don't think it's to far-fetched. Even if a site owner catches it, it's a mess to clean up.

Preventing the vendor from receiving commissions on the purchase of their own item is one particular way to _even out_ the scheme. Maybe there are other solutions, though.

**Comment by pippinsplugins** [comment]
That scenario makes much more sense. Maybe the best answer is to disable earning points on your own products in Points and Rewards.

**Comment by SDavisMedia** [comment]
That removes our ability to test with Points and Rewards... same thing you mentioned above for Commissions. Not as important of a plugin but still needs testing.

Can both be limited to just admins? If you're an admin, you can earn commissions on your own product as well as points. If you're not admin, you can't for either.

**Comment by pippinsplugins** [comment]
I'd be fine with limiting self-points and self-commissions to admins.

**Comment by pippinsplugins** [comment]
Or maybe we could just add a filter: `apply_filters( 'eddc_allow_self_commissions', true )`

**Comment by SDavisMedia** [comment]
Yea I like that idea.

**Comment by pippinsplugins** [comment]
@SDavisMedia could you pass that on to Jigar? I'll get this milestoned.

**Comment by SDavisMedia** [comment]
Sure thing.

**Comment by cklosowski** [comment]
Yes, I'm all for a filter here to enable earning points on your own products.

**Comment by cklosowski** [comment]
Going to use the filter here to execute this, and then I'll make the filter trigger inside the `EDD Dev Tools` repo.

**Comment by cklosowski** [comment]
If you're going to test this, you'll need to either not be on the latest EDD Dev tools or remove the filter for it temporarily for testing.

https://github.com/easydigitaldownloads/edd-dev-tools/blob/master/edd-dev-tools.php#L86

**Comment by mintplugins** [comment]
Working great here. 

Without dev tools I get no commissions when purchasing my own product. 

With dev tools on, I get commissions when purchasing my own product.

**Comment by cklosowski** [comment]
Updating the title, this doesn't use the `author`, it checks to see if the user id is in the recipients array.

**Comment by cklosowski** [comment]
@pippinsplugins @SDavisMedia ok, filter updated to detect if the user ID of the payment is an admin.

**Comment by pippinsplugins** [comment]
I changed the `manage_options` cap to `edit_shop_payments` so that shop accountants can test their own commissions too.
