### ISSUE TITLE
Migrate to custom database tables

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#134]
It's time to move all commission data out of wp_posts and wp_postmeta and into a dedicated table.

This will make the plugin significantly less of a burden on performance and will provide much greater flexibility for future features, such as payout logs, automated payouts, improved reporting, and more.

[EDD_Commision](https://github.com/easydigitaldownloads/EDD-Commissions/issues/133) will need to be introduced first and given a few months in the wild before we make this transition.

I propose the following table structure:
- id
- user_id
- amount
- status
- product_id
- payment_id
- date_created
- date_paid

The introduction of this table will also need to include a complete upgrade routine for migrating data away from the wp_posts and wp_postmeta tables. We will also need to include a backwards compatibility layer to catch all remaining post meta get/add/update/delete calls and get_posts() queries.

**Comment by davidsherlock** [comment]
@pippinsplugins, I would like to propose an addition to the above.

It would be extremely useful to store the original cart item sales price, item tax and total (including tax) used for the base commission calculation as commission metadata. Along with storying the cart array item name and production variation in the same manner as purchase data does (serialized) with the commission ID.

This keeps the data historically transactional for accounting purposes (even if purchase data is changed or items are added/removed from the purchase). 

This might be more of an 'edge' base but I am personally building a 'pure' marketplace where the sellers and buyers are separate from the marketplace/site itself, so instead of paying out commissions we charge a service fee like Envato and Etsy do, and having this data makes it easy to figure out service fees, taxes paid, etc.

**Comment by pippinsplugins** [comment]
That's a great idea @davidsherlock

**Comment by cklosowski** [comment]
Been thinking a lot about the comments above by @davidsherlock. Part of me loves it, part of me thinks it's just a ton of duplicated data. Both sides present pros and cons.

I personally don't think we should store that data on the commission record itself, as it will be just a bunch of duplicated data, and now that we offer the ability to change the item price and item tax on a payment, we could simply write some methods that update the commission record with the correct values if they are not paid yet.

If we DO store it on the commission record, then we not only have to update the commission amount, but all the 'duplicated' data from the payment record to the found commission, instead of simply recalculating the commission record.

Of all that, we'd just need the `cart_index` of the item purchased in order to figure all this out.

**Comment by cklosowski** [comment]
Here is my proposed table schema:
`id, user_id, amount, status, download_id, payment_id, cart_index, price_id, date_created, date_paid`

```
id - auto increment (and therefore is a primary & unique key

indexes for:
download_id - performance for get all commissions of a download
payment_id - performance for get all commissions of a payment
user_id - performance for get all commissions of a user
payment_id + cart_index - performance for getting a specific commission item from a payment
download_id + price_id - performance for getting all commissions for a specific price id
user_id + download_id - performance for getting all commissions for a user with a download ID
```

**Comment by davidsherlock** [comment]
@cklosowski, completely agree but let me give you a scenario where it would be useful.

With the forthcoming introduction of partial refunds, if an item from the cart is refunded or accidentally 'removed' from the cart/purchase, then the 'link' between the original purchase and the recorded commission is lost with no clear way to figure out how the store "arrived" at the commission amount (say for example if discount codes were used, thus altering the calculation). In an ideal world data wouldn't become corrupt like this, but since the commission record does not store all the data transactionally from a compliance and auditing standpoint it's not fully bulletproof and prone to issues if a store admin accidentally deletes anything.

What you propose for the cart index is fine, as long as there is an interface added to allow store owners the ability to re-select that "index" based on the purchase ID defined while editing or adding a commission.

If the cart data was stored alongside the commission record, if for whatever reason the commission records needed to be recalculated (say a store owner set the incorrect base calculation option and needed to batch update commission records), then within EDD tools menu could be a "recount unpaid commissions" type function with a date range to force a recalculation based on the new setting.

In rare cases cart_index could be end up being void if an item is removed from the original purchase record, meaning any "lookups" will fail. it might be a good fallback to store the base amounts used for the calculation as a separate field and (ideally) the download name/variation strings as a backup.

I guess I am simply suggesting this for an easy route to help me calculate my service fees on a per vendor (and commission) basis :)

**Comment by cklosowski** [comment]
@davidsherlock but with the cart ID, we can add hooks into the add/remove from payment actions that can update the records accurately at the time of modifying the payments.

I get your use case, but I see it as actually harder to keep a record in tact. Since now we have to update multiple layers of data on the payment AND then update those exact same records on the payments.

In the event that an item is removed from a payment, we can have it remove the commission record as well, in the event that we add an item, we can make it easier to 'add commissions' for this item.

All Im proposing is that instead of simply mirrioring the data (and making it harder to keep in tact), that we allow a better reference to the paymetn item, so that the commission record can always go get the data for the payment AND get updated when the item is updated.

**Comment by davidsherlock** [comment]
To be honest @cklosowski I am actually one of the biggest advocates of avoiding duplicate data for exactly those reasons, so it was hard for me to even suggest this initially.

Definitely storing the the price ID along with the download ID is a lot better than how it's done currently. I had to write a function that figured out the product variation in the cart by doing a string comparison (not ideal) for my current "solution" which is hacked together.

To conclude, I agree with what you suggest above and it seems the best way moving forward.

**Comment by cklosowski** [comment]
@davidsherlock I think your use case brings up a pain point we've had for quite a while, but as we move forward we can take this opportunity to make good on all the short comings we've been providing you with in past versions that the post meta relationships simply made it difficult to work through.

As we build it out, we'll come back here and make sure that everything we're doing allows something like what you want, to be sure that we're meeting the needs, since I think what you are requesting is really what most people want in the end :)

**Comment by pippinsplugins** [comment]
I agree with the proposed schema above.

@ghost1227 let's get started with that schema.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs This is ready for initial testing of a *NEW* installation. It creates the table on activation, so if you've tested this before, you'll need to deactivate/reactivate since the schema changed slightly to fix a few shortcomings and bugs.

So far this is what's been completed:
- Updated all references to `get_posts` to use `eddc_get_commissions`
- Updated all calls to `wp_query` to get from the DB Class
- Moved all but `is_renewal` to the main table (is_renewal still lives in the meta
- Updated the list table to use the new data
- Updated the Single view, edit and add to use the new format
- Updated the shortcodes and widgets to use the new data
- Added in a backwards compatibility layer for get_post_meta that looks for calls to `get_post_meta` that will reformat the data as needed (still need to work in a way to account for old commission IDs, but that will come after the migration is written)

**Comment by pippinsplugins** [comment]
@cklosowski this is working great so far!

One small issue I noticed: you cannot edit the amount of a commission. The amount can be changed from the view screen but the change does not save. The rate saves fine but not the amount.

**Comment by pippinsplugins** [comment]
@cklosowski looks like batch export is broken now, primarily because of WP_DEBUG being enabled and deprecated notices being thrown.

Let's do two things:

1. Only trigger notices if not doing ajax
2. Update the batch export to not use deprecated methods :)

It also triggered this notice:

PHP Notice: Trying to get property of non-object in /app/public/wp-content/plugins/edd-commissions/includes/admin/classes/class-batch-commissions-payout.php on line 95

**Comment by davidsherlock** [comment]
Will give this a test run tomorrow and report back! 

Regardless, nice work Chris - definitely a need migration!

**Comment by cklosowski** [comment]
A migration routine will be added to this branch later, for now it's existing in `issue/134-migration`, so that I can keep fixing issues found in new installs, while still working on the migration. I'll merge that work into `issue/134` when it's ready.

**Comment by mintplugins** [comment]
Just a note - when I expired an All Access Pass that needed commissions I got this error:
```
Notice: Trying to get property of non-object in /Users/philjohnston/Documents/wps/edd2.dev/wp-content/plugins/EDD-Commissions/includes/email-functions.php on line 106
```

Not sure if that's a problem with Commissions or All Access yet but digging in. Just wanted to log it.

**Comment by mintplugins** [comment]
Actually I am getting that error upon every commission generation - even with All Access deactivated (so "normal" commissions). 

No commissions seem to be getting generated at all for me.

**Comment by pippinsplugins** [comment]
@mintplugins deactivate and reactivate Commissions. That will trigger the new table to be created.

**Comment by mintplugins** [comment]
This is working great for me with the latest commits using custom commission meta as well. 

Working great with All Access issue 115:
https://github.com/easydigitaldownloads/edd-all-access/issues/115

**Comment by cklosowski** [comment]
Ok the migration utility via WPCLI is ready for testing.

This currently moves all data over to the custom table, including all meta data that's not core data, and then also it will remove the data from `wp_posts` and `wp_postmeta` if you choose to (there is a prompt for a `y/n` response)

To run it, `wp edd-commissions migrate_commissions`. If you are running in a subsite you need to include `--url=domain.com/sub-site`

**Comment by cklosowski** [comment]
@pippinsplugins the Exporter and Payout Generator should be fixed now.

**Comment by pippinsplugins** [comment]
@cklosowski PHP warning:

call_user_func_array() expects parameter 1 to be a valid callback, class 'EDDC' does not have a method 'eddc_add_fes_functionality'

**Comment by pippinsplugins** [comment]
Looks like the migration worked! There is a PHP warning though after running it:

WordPress database error Column 'type' cannot be null for query INSERT INTO `wp_30_edd_commissions` (`user_id`, `amount`, `status`, `download_id`, `payment_id`, `cart_index`, `price_id`, `date_created`, `date_paid`, `type`, `rate`, `currency`) VALUES (46, 6, 'unpaid', 214, 440, 0, 0, '2017-06-13 12:38:52', '', NULL, 50, 'USD') made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, edd_get_actions, do_action('edd_commissions_migration'), WP_Hook->do_action, WP_Hook->apply_filters, eddc_commissions_migration, EDD_DB->insert, QM_DB->query

**Comment by pippinsplugins** [comment]
@cklosowski looks like we have a fatal error when EDD core is not active.

Fatal error: Class 'EDD_DB' not found in /Users/pippin/Sites/edd/wp-content/plugins/edd-commissions/includes/classes/class-edd-commission-db.php on line 15

**Comment by cklosowski** [comment]
Fixed @pippinsplugins

**Comment by cklosowski** [comment]
This has been merged into `release/3.4` after testing. We'll leave the issue open to keep things up for discussion.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Just tested this on a real site and it worked almost perfectly. Everything looks good except for the date:
<img width="914" alt="screen shot 2017-06-16 at 3 39 19 pm" src="https://user-images.githubusercontent.com/1034109/27243961-ff712020-52a9-11e7-868a-2f7c3218ecf6.png">

Every record was given the same date (today).

**Comment by cklosowski** [comment]
Weird. We're using payment data to determine that I'll dig into it.

**Comment by pippinsplugins** [comment]
Oh, we also have a small discrepancy.

Prior to migration, this site's unpaid total was `$277.50`. After migration it's showing as `$270.00`.

**Comment by cklosowski** [comment]
I'd verify the previous data is right. This is using a MySQL sum so zero
logic is performed outside of the query.

**Comment by pippinsplugins** [comment]
And we're good! Everything matches up now!

**Comment by pippinsplugins** [comment]
This is now running live on pippinsplugins.com!

**Comment by pippinsplugins** [comment]
There have been two real sales on pippinsplugins.com that generated commissions. Both worked perfectly!

I'm going to begin testing on the EDD staging site.

**Comment by pippinsplugins** [comment]
Stats on staging prior to migration:

- Total commission records: 31748
- Unpaid count: 1109
- Paid count: 29561
- Revoked count: 1078
- Unpaid earnings: $26,232.58

**Comment by pippinsplugins** [comment]
@cklosowski looks like we need to add a fallback for when payments don't have a currency detected.

WordPress database error Column 'currency' cannot be null for query INSERT INTO `edd_edd_commissions` (`user_id`, `amount`, `status`, `download_id`, `payment_id`, `cart_index`, `price_id`, `date_created`, `date_paid`, `type`, `rate`, `currency`) VALUES (2676, 34.300000, 'paid', 331541, 0, 0, 0, '2014-10-31 17:03:40', '', 'percentage', 70.000000, NULL) made by include('phar:///usr/local/wp-cli/wp-cli-1.1.0.phar/php/boot-phar.php'), include('phar:///usr/local/wp-cli/wp-cli-1.1.0.phar/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, EDD_Commissions_CLI->migrate_commissions, EDD_DB->insert

**Comment by pippinsplugins** [comment]
Migration on staging complete.

Old Records: 31748
New Records: 31747

I'm guessing the missing new record is due to the error above where the insert failed due to the missing currency.

After migration:

- Total commission records: 31747
- Unpaid count: 1109
- Paid count: 29560
- Revoked count: 1078
- Unpaid earnings: $26,232.58

Only one record not accounted for!

**Comment by pippinsplugins** [comment]
One other little issue: the upgrade notice message didn't go away after completing the migration.

**Comment by cklosowski** [comment]
@pippinsplugins did you run via CLI or via Interface?

**Comment by pippinsplugins** [comment]
CLI

**Comment by pippinsplugins** [comment]
Seems the commission record that failed was for a payment record that no longer exists.

**Comment by cklosowski** [comment]
@pippinsplugins ok, in instances like that I think we should still migrate the commission record, just we'll have to do a check if the payment exists before using the payment record. I'll get that fixed up after I get the EDD 2.8 release worked up.

**Comment by pippinsplugins** [comment]
I agree

**Comment by pippinsplugins** [comment]
Looks like we still need to update the list table's `get_meta_query()` method as it's trying to call the old postmeta.

**Comment by pippinsplugins** [comment]
And `get_tax_query()`.

**Comment by cklosowski** [comment]
@pippinsplugins yeah, we don't even need those anymore :) I've removed them.

**Comment by pippinsplugins** [comment]
@cklosowski filtering by a payment doesn't work because the `get_commissions()` method never sets up the `payment_id=%d` where clause.

**Comment by pippinsplugins** [comment]
Looks like it also needs to support a `download_id` parameter.

**Comment by cklosowski** [comment]
I just added the download parameter: https://github.com/easydigitaldownloads/EDD-Commissions/commit/c4c941d54dc1316c5018749fd67bc23792f39497#diff-e5cab8dada7ae4728db8b82b1a0921f5R196

**Comment by cklosowski** [comment]
@pippinsplugins you haven't ever been able to filter the commissions list table by the payment ID. Only vendor and download. Clicking on payment IDs just goes to the payment, and searching is only supported for the vendor names.

**Comment by cklosowski** [comment]
Ok `issue/134` has a prompt for UI based upgrade routine to wait to delete the legacy data, and it added in `payment_id` into the `parse_where` method.

**Comment by pippinsplugins** [comment]
A couple of small changes requested on PR. I'll make them later today or tomorrow, just leaving them for records' sake.

**Comment by pippinsplugins** [comment]
Changes made.

**Comment by pippinsplugins** [comment]
Attempting to delete legacy data gave me an error:


WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1 for query DELETE FROM wp_30_postmeta WHERE post_id IN () made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, edd_get_actions, do_action('edd_remove_legacy_commissions'), WP_Hook->do_action, WP_Hook->apply_filters, eddc_remove_legacy_commissions, QM_DB->query

**Comment by pippinsplugins** [comment]
Fixed error.

**Comment by pippinsplugins** [comment]
We need to make it so the upgrade DB notice only shows if there are legacy commissions detected. If there are no legacy commissions, there is no reason to run the upgrade/

**Comment by pippinsplugins** [comment]
I've found a few places that are still calling `get_post_meta()` on commission records. These should be updated to use `EDD_Commission::get_meta()`.

Note: these calls to `get_post_meta()` are designed to still work but we do need to go ahead and update them.

**Comment by pippinsplugins** [comment]
Ok I believe I've caught all cases of get_post_meta() that needed updated.

Note: I left a few that were in old upgrade routines and unused code for PayPal Adaptive Payments.

**Comment by pippinsplugins** [comment]
We need to add a layer for re-routing `add_post_meta()`, `update_post_meta()`, and `delete_post_meta()` to our new custom tables.

**Comment by pippinsplugins** [comment]
We also need to add a layer for get/update/add/delete for terms as commission statuses were stored as a taxonomy term.
