### ISSUE TITLE
Missing Span ID + Legend Wrap

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#160]
The "PayPal Email Address" heading is missing a Span ID and Legend wrap, meaning the heading can't be targeted for styling to match the other form elements on the EDD Account page.

**Comment by pippinsplugins** [comment]
We'll get that fixed in the next point release.

**Comment by ghost1227** [comment]
@pippinsplugins I think there's a bigger issue here with EDD core... Right now, the commissions email field is being hooked to `edd_profile_editor_after_password`, which results in the following:

<img width="802" alt="screen shot 2017-04-06 at 9 37 23 am" src="https://cloud.githubusercontent.com/assets/36433/24759955/c142798c-1aac-11e7-8267-56575477f8d1.png">

I can't say what the correct placement for the email field is, but I'm pretty confident it's not in a fieldset labelled 'Change your Password'. Unfortunately, we don't have a great hook to replace it with, as the only actions currently present in that shortcode are at the end of each fieldset and at the top of the entire form. I think we should add an action either between the address and password fieldsets or after the password fieldset so that we can add new fieldsets properly (and therefore new legends). Simply switching the current code to a legend results in an even worse experience, as it ends up losing separation between password fields and email field entirely:

<img width="804" alt="screen shot 2017-04-06 at 9 42 41 am" src="https://cloud.githubusercontent.com/assets/36433/24760173/8323a13e-1aad-11e7-86ba-3ed79528a407.png">

**Comment by ghost1227** [comment]
@pippinsplugins thoughts?

**Comment by pippinsplugins** [comment]
@ghost1227 how about adding a new fieldset for this so that it is its own section?

**Comment by ghost1227** [comment]
@pippinsplugins That's my point. Right now there isn't anywhere to ADD a new fieldset. The existing actions are all either inside the pre-existing fieldsets or before the first one. We need to add new hooks to core to make it possible.

**Comment by ghost1227** [comment]
Note that the PR depends on https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5652

**Comment by ghost1227** [comment]
Now that the dependent PR is closed, can we get this one merged too?

**Comment by ghost1227** [comment]
@pippinsplugins @SDavisMedia just pinging to keep eyes on this

**Comment by pippinsplugins** [comment]
@ghost1227 Looks like you missed my PR review. We need a version check: https://github.com/easydigitaldownloads/EDD-Commissions/pull/217

**Comment by ghost1227** [comment]
@pippinsplugins I did miss that, my apologies. Just updated the PR, but I'm not sure that it's ideal... the whole fieldset thing won't actually be valid pre-2.7.8, but if we don't display ANYTHING, we're dropping important functionality. Thoughts?

**Comment by pippinsplugins** [comment]
I think we should leave it as it was (before this PR) and only change the markup for 2.7.8+.

**Comment by ghost1227** [comment]
OK, that was what i was thinking

**Comment by ghost1227** [comment]
@pippinsplugins How's that work for you?

**Comment by mintplugins** [comment]
This looks great to me!

I have tested on both pre 2.7.8 and "post" (by changing the version of EDD manually on my local). Output looks good in both cases and fulfills the initial request to add the ID and legend wrap.

**Comment by ghost1227** [comment]
Woot! Thanks @mintplugins!
