### ISSUE TITLE
Admin table styling issues

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#236]
This is _somewhat_ linked to FES, but since the shortcodes are output by commissions it felt better suited to here. Within the FES vendor card view, the commissions tab shows the commissions data pretty much dumped on the page like this:

![screenshot 2017-05-09 21 03 42](https://cloud.githubusercontent.com/assets/22668877/25870192/206332b8-34fb-11e7-9594-f09b4a6510e9.png)

I feel this layout could be improved a lot visually by giving the tables a striped look and laying the elements out better to make it more clear for the admins.

In line with the responsive tabs, it would be nice to have basic responsive tables as well.

**Comment by pippinsplugins** [comment]
We can fix this for sure!

**Comment by cklosowski** [comment]
I'm extremely hesitant to make styling changes here. The function that FES uses to display this information is already wrapped in all the necessary markup that's required, however if we do any changes to this marketup at all, we'll be affecting front end commissions views using the shortcodes, since the functions in use are the ones the shortcodes call.

My suggestion would be to forgo using any of the current markup and functions and rebuild this page from the ground up using the EDD Core built in styles and configurations for the 'card views'.

**Comment by cklosowski** [comment]
As an example, this is what EDD Commissions shows like on a customer card view (very similar to the vendor admin view)

<img width="848" alt="screen shot 2017-06-19 at 2 56 08 pm" src="https://user-images.githubusercontent.com/1390124/27307958-34daff48-5501-11e7-85f7-699850afc1b7.png">

Personally it seems like FES took the short cut route just trying to use the front end markup function used in the shortcode, for an admin view, I feel this is better suited as an FES issue, to completely fix it's markup, or find a way to simply use the EDD Commissions function on it's own view.

**Comment by cklosowski** [comment]
After thinking more on this, I'm closing it and leaving it up to FES to build this. I think that is where it belongs, since the function being used here is not intended for admin use (as it's for the Front end shortcode of commissions).
