### ISSUE TITLE
Some server configs don't allow the download of the batch export file

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#63]
On some hosting configurations (like the EDD Pagely setup), the file to download the Mass pay file ends in a 502(?) so the file doesn't download. This results in having to manually download the file, which, does not contain the date on it since that's part of the Core EDD Batch Export class processing the download.

**Comment by cklosowski** [comment]
The date is on the payout i'm looking at:
![screen shot 2015-07-22 at 11 41 41 am](https://cloud.githubusercontent.com/assets/1390124/8834003/ac90a432-3066-11e5-8720-62e851a3a775.png)

**Comment by cklosowski** [comment]
@pippinsplugins You sure you're on the right branches of everything? I'm getting the date...those dates are actually controlled by the Core EDD batch exporter.

**Comment by cklosowski** [comment]
Updated the title and the description to reflect the real issue, it's in the download process being cut short by the server config.

**Comment by cklosowski** [comment]
Cannot replicate on Pagly staging.

**Comment by cklosowski** [comment]
So the issue isn't in the batch export process, it's in the file download process. When the batch is done, the core batch processor goes through and forces a download of the temp file, with the date appended. Since this is erroring on the hosting platform, the dates aren't appended. I've not been able to replicate on the pagely staging environment, but it's repeatable on multiple accounts on their live sites. 

@pippinsplugins What else can you think of doing here? I could go in and manually set it to not mark items as paid (just comment out the line) and try it on the production site, see if that works.

**Comment by cklosowski** [comment]
Come to think of it, that waiting until the end to mark things as paid might be the issue...that's a lot of queries hitting the DB consecutively, which could be why I didn't see the issue in staging.

**Comment by pippinsplugins** [comment]
Any test I can run to help track it down?

**Comment by cklosowski** [comment]
We'd just need to see if there was any errors in the PHP error log at the time of export...but we'd need the whole mark as paid thing to run as well. So that's maybe something we'd have to try at our next payouts?

**Comment by pippinsplugins** [comment]
Sure thing.

**Comment by pippinsplugins** [comment]
Live EDD site is still seeing a gateway timeout here:
![screen shot 2015-09-15 at 9 06 52 am](https://cloud.githubusercontent.com/assets/1034109/9878603/2770f5ec-5b89-11e5-856d-544f60faee8e.png)

**Comment by pippinsplugins** [comment]
This hasn't showed up again. CLosing.
