### ISSUE TITLE
Flat rate amounts less than 1 are incorrectly converted

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Commissions#80]
Set up a flat rate commission of less than $1 (for example .25), save the download, and the commission gets multiplied by 100 and saved as 25. We just need to check that the commission type is percentage before doing the conversion.

**Comment by chriscct7** [comment]
It should be noted that 25 cents is not a valid commission amount if they
use PayPal to pay out. So while this may be a bug it prevented people from
setting commissions that can't be paid out. For example 10 commissions of 1
cent is 10 cents which is less than the gateway supported minimum of 50
cents. If we remove this we need to put in logic that only pays out what
can be paid out (ie if sending to PayPal in csv then don't export vendors
whose payout is under 50 cents total) or if instant split payment don't
support commission rates that are under 50 cents flat or 50 cents as a
percentage after taxes and discounts

**Comment by mindctrl** [comment]
@chriscct7 have a good link where the minimums are detailed?

**Comment by chriscct7** [comment]
No, because not only does it vary for each gateway, it varies for each country, and on settings. 

For example, in the United States, PayPal Adaptive, the minimum transfer amount is $0.02, the average fee is 2.9% + 30 cents

US PayPal Adaptive Chained (seller pays fees): Minimum 2 cent commission (after all discounts + taxes)
US PayPal Adaptive Chained (primary receiver pays fees): Minimum 2 cent commission (after all discounts + taxes)
US PayPal Adaptive Chained (all receivers pays fees): Minimum 33 cents commission (after all discounts + taxes based on a 2.9% + 30 cents on the order total + 0.02 balance transfer minimum in US)
US PayPal Adaptive Parallel (all receivers pays fees): Minimum 33 cents commission (after all discounts + taxes based on a 2.9% + 30 cents on the order total + 0.02 balance transfer minimum in US)

And those just assume that you're transferring the money to a US based vendor. Transfer limits change for every single country in PayPal. And the minimum transfer amounts themselves change depending on which country the primary account holder is in. Or that you can negotiate other rates on the transaction cost.

There's an infinite number of these combinations, but the bottom line is there's no combination where 50 cents is below the minimum.

For example, if you parallel send someone 30 cents, the person gets a commission of $0, because its less than the fee.

**Comment by pippinsplugins** [comment]
I'm fine with allowing less than $1 commissions and just noting the PayPal limitations in the documentation.
